from __future__ import annotations

import json
import re
import shutil
import subprocess
import tempfile
from pathlib import Path
from uuid import uuid4

from sqlalchemy import select
from sqlalchemy.orm import selectinload

from aegaeon.database.models import ArtifactRecord, ProjectRecord, TaskRecord
from aegaeon.database.session import Database
from aegaeon.projects.integration import IntegrationConflict
from aegaeon.protocol.schemas import ArtifactRead, ProjectCreate, ProjectRead, TaskRead


class ProjectManager:
    def __init__(self, database: Database, projects_dir: Path) -> None:
        self.database = database
        self.projects_dir = projects_dir.resolve()
        self.projects_dir.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def _derive_name(prompt: str) -> str:
        first_line = prompt.strip().splitlines()[0].strip()
        cleaned = re.sub(r"^(build|create|make)\s+(me\s+)?(an?\s+)?", "", first_line, flags=re.I)
        return cleaned[:70].rstrip(" .") or "Untitled project"

    def create(self, request: ProjectCreate) -> ProjectRead:
        project_id = f"project-{uuid4().hex[:10]}"
        root = (self.projects_dir / project_id).resolve()
        if not root.is_relative_to(self.projects_dir):
            raise ValueError("project path escapes data directory")
        repo = root / "repo"
        (root / "artifacts").mkdir(parents=True)
        (root / "logs").mkdir()
        (root / "AEGAEON").mkdir()
        repo.mkdir()
        name = request.name or self._derive_name(request.prompt)
        metadata = {
            "id": project_id,
            "name": name,
            "prompt": request.prompt,
            "status": "draft",
            "strategy": request.strategy,
            "execution_mode": request.execution_mode.value,
            "worker_count": request.worker_count,
            "selected_model": request.selected_model,
        }
        (root / "project.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")
        (root / "AEGAEON" / "history.json").write_text("[]\n", encoding="utf-8")
        (repo / ".gitignore").write_text(
            ".pytest_cache/\n__pycache__/\n*.pyc\n.venv/\n", encoding="utf-8"
        )
        (repo / "README.md").write_text(f"# {name}\n\nGenerated by AEGAEON.\n", encoding="utf-8")
        self._git(repo, "init", "-b", "main")
        self._git(repo, "config", "user.name", "AEGAEON")
        self._git(repo, "config", "user.email", "aegaeon@localhost")
        self._git(repo, "add", ".")
        self._git(repo, "commit", "-m", "AEGAEON: initialize canonical workspace")

        options = request.model_dump(mode="json", exclude={"prompt", "name", "strategy"})
        record = ProjectRecord(
            id=project_id,
            name=name,
            prompt=request.prompt,
            strategy=request.strategy.value,
            workspace_path=str(repo),
            options=options,
        )
        with self.database.session() as session:
            session.add(record)
        return self.get(project_id)

    def list(self) -> list[ProjectRead]:
        with self.database.session() as session:
            projects = session.scalars(
                select(ProjectRecord)
                .options(selectinload(ProjectRecord.tasks))
                .order_by(ProjectRecord.created_at.desc())
            ).all()
            return [ProjectRead.model_validate(item) for item in projects]

    def get(self, project_id: str) -> ProjectRead:
        with self.database.session() as session:
            project = session.scalar(
                select(ProjectRecord)
                .where(ProjectRecord.id == project_id)
                .options(selectinload(ProjectRecord.tasks))
            )
            if not project:
                raise KeyError(project_id)
            return ProjectRead.model_validate(project)

    def tasks(self, project_id: str) -> list[TaskRead]:
        with self.database.session() as session:
            items = session.scalars(
                select(TaskRecord)
                .where(TaskRecord.project_id == project_id)
                .order_by(TaskRecord.sequence)
            ).all()
            return [TaskRead.model_validate(item) for item in items]

    def task(self, task_id: str) -> TaskRead:
        with self.database.session() as session:
            task = session.get(TaskRecord, task_id)
            if not task:
                raise KeyError(task_id)
            return TaskRead.model_validate(task)

    def artifacts(self, project_id: str) -> list[ArtifactRead]:
        with self.database.session() as session:
            items = session.scalars(
                select(ArtifactRecord)
                .where(ArtifactRecord.project_id == project_id)
                .order_by(ArtifactRecord.created_at.desc())
            ).all()
            return [ArtifactRead.model_validate(item) for item in items]

    def repo_path(self, project_id: str) -> Path:
        project = self.get(project_id)
        path = Path(project.workspace_path).resolve()
        if not path.is_relative_to(self.projects_dir):
            raise ValueError("project repository is outside the managed directory")
        return path

    def current_revision(self, project_id: str) -> str:
        return self._git(self.repo_path(project_id), "rev-parse", "HEAD").stdout.strip()

    def integrate_files(
        self,
        project_id: str,
        task_key: str,
        title: str,
        files: dict[str, str],
        base_revision: str | None = None,
    ) -> tuple[list[str], str]:
        repo = self.repo_path(project_id)
        prepared = self._prepare_concurrent_merge(repo, files, base_revision)
        modified: list[str] = []
        for relative_name, content in prepared.items():
            target = self._safe_target(repo, relative_name)
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            modified.append(Path(relative_name).as_posix())
        self._git(repo, "add", "--all")
        patch = self._git(repo, "diff", "--cached", "--binary", "HEAD", check=False).stdout
        if not patch.strip():
            return modified, ""
        self._git(repo, "commit", "-m", f"AEGAEON({task_key}): {title}")
        return modified, patch

    def _prepare_concurrent_merge(
        self, repo: Path, files: dict[str, str], base_revision: str | None
    ) -> dict[str, str]:
        prepared = dict(files)
        for relative_name in prepared:
            self._safe_target(repo, relative_name)
        current_revision = self._git(repo, "rev-parse", "HEAD").stdout.strip()
        if not base_revision or base_revision == current_revision:
            return prepared
        if not re.fullmatch(r"[0-9a-f]{40}", base_revision):
            raise IntegrationConflict(sorted(files), "invalid base revision")
        ancestor = self._git(
            repo, "merge-base", "--is-ancestor", base_revision, current_revision, check=False
        )
        if ancestor.returncode != 0:
            raise IntegrationConflict(sorted(files), "base revision is not an ancestor of HEAD")
        changed_output = self._git(
            repo, "diff", "--name-only", f"{base_revision}..{current_revision}"
        ).stdout
        changed = {line.strip() for line in changed_output.splitlines() if line.strip()}
        conflicts: list[str] = []
        for relative_name in sorted(set(prepared) & changed):
            base = self._content_at(repo, base_revision, relative_name)
            target = self._safe_target(repo, relative_name)
            current = target.read_text(encoding="utf-8") if target.is_file() else ""
            proposed = prepared[relative_name]
            if proposed == current:
                prepared[relative_name] = current
                continue
            if proposed == base:
                prepared[relative_name] = current
                continue
            merged = self._three_way_merge(repo, current, base, proposed)
            if merged is None:
                conflicts.append(relative_name)
            else:
                prepared[relative_name] = merged
        if conflicts:
            raise IntegrationConflict(conflicts, "three-way merge produced conflict markers")
        return prepared

    @staticmethod
    def _safe_target(repo: Path, relative_name: str) -> Path:
        relative = Path(relative_name.replace("\\", "/"))
        if relative.is_absolute() or ".." in relative.parts or ".git" in relative.parts:
            raise ValueError(f"unsafe project file path: {relative_name}")
        target = (repo / relative).resolve()
        if not target.is_relative_to(repo):
            raise ValueError(f"file path escapes repository: {relative_name}")
        return target

    @classmethod
    def _content_at(cls, repo: Path, revision: str, relative_name: str) -> str:
        result = cls._git(repo, "show", f"{revision}:{relative_name}", check=False)
        return result.stdout if result.returncode == 0 else ""

    @staticmethod
    def _three_way_merge(repo: Path, current: str, base: str, proposed: str) -> str | None:
        with tempfile.TemporaryDirectory(prefix="aegaeon-merge-") as temporary:
            root = Path(temporary)
            current_path = root / "current"
            base_path = root / "base"
            proposed_path = root / "proposed"
            current_path.write_text(current, encoding="utf-8")
            base_path.write_text(base, encoding="utf-8")
            proposed_path.write_text(proposed, encoding="utf-8")
            result = subprocess.run(
                [
                    "git",
                    "merge-file",
                    "-p",
                    str(current_path),
                    str(base_path),
                    str(proposed_path),
                ],
                cwd=repo,
                check=False,
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
                timeout=30,
            )
            return result.stdout if result.returncode == 0 else None

    def file_tree(self, project_id: str) -> list[dict[str, object]]:
        repo = self.repo_path(project_id)
        output: list[dict[str, object]] = []
        for path in sorted(repo.rglob("*")):
            if ".git" in path.parts or not path.is_file():
                continue
            relative = path.relative_to(repo).as_posix()
            output.append({"path": relative, "size": path.stat().st_size})
        return output

    def export_zip(self, project_id: str) -> Path:
        repo = self.repo_path(project_id)
        export_root = repo.parent / f"{project_id}-export"
        archive = Path(shutil.make_archive(str(export_root), "zip", root_dir=repo))
        return archive

    @staticmethod
    def _git(repo: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            ["git", *args],
            cwd=repo,
            check=check,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=30,
        )
